import herobg from './images/hero.png'
import jobcardone from './images/j1.png'
import jobcardtwo from './images/j2.png'
import jobcardthree from './images/j3.png'
import jobcardfour from './images/j4.png'
import jobcardfive from './images/j5.png'
import jobcardsix from './images/j6.png'
import jobcardseven from './images/j7.png'
import jobcardeight from './images/j8.png'
import jobcardnine from './images/j9.png'
import infoimg from './images/a.png'
import reviewone from './images/u1.png'
import reviewtwo from './images/u2.png'
import reviewthree from './images/u3.png'

export {reviewone,reviewtwo,reviewthree ,infoimg,herobg, jobcardone, jobcardtwo, jobcardthree, jobcardfour, jobcardfive, jobcardsix, jobcardseven, jobcardeight, jobcardnine}
